## FIN 5350 Homework 2
#### Jesse Baker

In [9]:
## First import numpy
import numpy as np
from scipy.stats import binom

## Call Payoff Function
def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

## Put Payoff Function
def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

In [74]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))                    
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d)) #delta
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j+1, t+1]) - (d * Ct[j, t+1])) / (u - d))
            
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))
        print("\n")            
            
    return Ct[0,0]

### Problem 1
##### a.

In [71]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))                    
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d)) #delta
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j+1, t+1]) - (d * Ct[j, t+1])) / (u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))
        print("\n")
                    
            
    return Ct[0,0]

In [72]:
r = 0.08   ### time step
v = 0.30   ### volatility 
q = 0.0    ### dividend
T = .5
n = 1      ### periods
h = T / n
S = 100.0  ### spot price 
K = 105.0  ### strike price

In [73]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)
callPrc

[[100. 130.]
 [  0.  80.]]


[[11.568 25.   ]
 [ 0.     0.   ]]


[[0.5 0. ]
 [0.  0. ]]


[[-38.432   0.   ]
 [  0.      0.   ]]




11.568422433907068

### Problem 1
##### b.

In [78]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))                    
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d)) #delta
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j+1, t+1]) - (d * Ct[j, t+1])) / (u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))
        print("\n")
                    
            
    return Ct[0,0]

In [79]:
r = 0.08   ### time step
v = 0.30   ### volatility 
q = 0.0    ### dividend
T = .5
n = 1      ### periods
h = T / n
S = 100.0  ### spot price 
K = 105.0  ### strike price

In [80]:
putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff, verbose = True)
putPrc

[[100. 130.]
 [  0.  80.]]


[[12.451  0.   ]
 [ 0.    25.   ]]


[[-0.5  0. ]
 [ 0.   0. ]]


[[62.451  0.   ]
 [ 0.     0.   ]]




12.45131354490101

### Problem 2
##### a.

In [82]:
r = 0.08   ### time step
v = 0.30   ### volatility 
q = 0.0    ### dividend
T = .5
n = 1      ### periods
h = T / n
S = 100.0  ### spot price 
K = 95.0  ### strike price

In [83]:
putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff, verbose = True)
putPrc

[[100. 130.]
 [  0.  80.]]


[[ 7.471  0.   ]
 [ 0.    15.   ]]


[[-0.3  0. ]
 [ 0.   0. ]]


[[37.471  0.   ]
 [ 0.     0.   ]]




7.470788126940606

##### b.

In [84]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)
callPrc

[[100. 130.]
 [  0.  80.]]


[[16.196 35.   ]
 [ 0.     0.   ]]


[[0.7 0. ]
 [0.  0. ]]


[[-53.804   0.   ]
 [  0.      0.   ]]




16.195791407469894

In [85]:
Arbitrage = 17 - callPrc
Arbitrage
#We short the stock

0.8042085925301059

##### c.

In [66]:
Arbitrage1 = 15.50 - callPrc
Arbitrage1
#We long the stock

-0.6957914074698941

### Problem 3

In [105]:
r = 0.08   ### time step
v = 0.30   ### volatility 
q = 0.0    ### dividend
T = 1
n = 2      ### periods
h = T / n
S = 100.0  ### spot price 
K = 95.0  ### strike price

In [106]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)

[[100. 130. 169.]
 [  0.  80. 104.]
 [  0.   0.  64.]]


[[19.994 38.725 74.   ]
 [ 0.     4.165  9.   ]
 [ 0.     0.     0.   ]]


[[0.691 1.    0.   ]
 [0.    0.225 0.   ]
 [0.    0.    0.   ]]


[[-49.127 -91.275   0.   ]
 [  0.    -13.835   0.   ]
 [  0.      0.      0.   ]]




### Problem 4

In [88]:
S = 80
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n

In [101]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)

[[130.   169.   219.7  285.61]
 [  0.   104.   135.2  175.76]
 [  0.     0.    83.2  108.16]
 [  0.     0.     0.    66.56]]


[[ 46.576  78.934 127.2   190.61 ]
 [  0.     21.971  42.7    80.76 ]
 [  0.      0.      5.818  13.16 ]
 [  0.      0.      0.      0.   ]]


[[0.876 1.    1.    0.   ]
 [0.    0.709 1.    0.   ]
 [0.    0.    0.316 0.   ]
 [0.    0.    0.    0.   ]]


[[-67.351 -90.066 -92.5     0.   ]
 [  0.    -51.793 -92.5     0.   ]
 [  0.      0.    -20.502   0.   ]
 [  0.      0.      0.      0.   ]]




In [90]:
S = 90
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n

In [102]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)

[[130.   169.   219.7  285.61]
 [  0.   104.   135.2  175.76]
 [  0.     0.    83.2  108.16]
 [  0.     0.     0.    66.56]]


[[ 46.576  78.934 127.2   190.61 ]
 [  0.     21.971  42.7    80.76 ]
 [  0.      0.      5.818  13.16 ]
 [  0.      0.      0.      0.   ]]


[[0.876 1.    1.    0.   ]
 [0.    0.709 1.    0.   ]
 [0.    0.    0.316 0.   ]
 [0.    0.    0.    0.   ]]


[[-67.351 -90.066 -92.5     0.   ]
 [  0.    -51.793 -92.5     0.   ]
 [  0.      0.    -20.502   0.   ]
 [  0.      0.      0.      0.   ]]




In [93]:
S = 110
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n

In [103]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)\

[[130.   169.   219.7  285.61]
 [  0.   104.   135.2  175.76]
 [  0.     0.    83.2  108.16]
 [  0.     0.     0.    66.56]]


[[ 46.576  78.934 127.2   190.61 ]
 [  0.     21.971  42.7    80.76 ]
 [  0.      0.      5.818  13.16 ]
 [  0.      0.      0.      0.   ]]


[[0.876 1.    1.    0.   ]
 [0.    0.709 1.    0.   ]
 [0.    0.    0.316 0.   ]
 [0.    0.    0.    0.   ]]


[[-67.351 -90.066 -92.5     0.   ]
 [  0.    -51.793 -92.5     0.   ]
 [  0.      0.    -20.502   0.   ]
 [  0.      0.      0.      0.   ]]




In [96]:
S = 120
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n

In [97]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)

[[120.   156.   202.8  263.64]
 [  0.    96.   124.8  162.24]
 [  0.     0.    76.8   99.84]
 [  0.     0.     0.    61.44]]


[[ 37.345  65.934 110.3   168.64 ]
 [  0.     15.417  32.3    67.24 ]
 [  0.      0.      2.14    4.84 ]
 [  0.      0.      0.      0.   ]]


[[0.842 1.    1.    0.   ]
 [0.    0.628 1.    0.   ]
 [0.    0.    0.126 0.   ]
 [0.    0.    0.    0.   ]]


[[-63.688 -90.066 -92.5     0.   ]
 [  0.    -44.903 -92.5     0.   ]
 [  0.      0.     -7.54    0.   ]
 [  0.      0.      0.      0.   ]]




In [99]:
S = 130
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n

In [100]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)

[[130.   169.   219.7  285.61]
 [  0.   104.   135.2  175.76]
 [  0.     0.    83.2  108.16]
 [  0.     0.     0.    66.56]]


[[ 46.576  78.934 127.2   190.61 ]
 [  0.     21.971  42.7    80.76 ]
 [  0.      0.      5.818  13.16 ]
 [  0.      0.      0.      0.   ]]


[[0.876 1.    1.    0.   ]
 [0.    0.709 1.    0.   ]
 [0.    0.    0.316 0.   ]
 [0.    0.    0.    0.   ]]


[[-67.351 -90.066 -92.5     0.   ]
 [  0.    -51.793 -92.5     0.   ]
 [  0.      0.    -20.502   0.   ]
 [  0.      0.      0.      0.   ]]




As S increases, delta increases at a decreasing rate.

### Problem 5
##### a.

In [123]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))                    
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d)) #delta
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j+1, t+1]) - (d * Ct[j, t+1])) / (u - d))
            
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))
        print("\n")            
            
    return Ct[0,0]

### a.

In [116]:
S = 100
K = 95
r = .08
v = .3
q = 0
T = 1
n = 3
h = T / n

In [124]:
callPrc1 = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = False)
callPrc1

18.28255220737056

There is no early excersize.

### b.

In [120]:
callPrc2 = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = False)
callPrc2

18.28255220737056

### c.

In [128]:
putPrc1 = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff, verbose = False)
putPrc1

5.97860511410097

Put call parity will hold.

In [127]:
parity = S - (K * np.exp(( - r * T)))
parity

12.3039470932696

In [129]:
parity1 = callPrc2 - putPrc1
parity1

12.30394709326959

### d.

In [134]:
def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = False):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
   
   
   ## Arrays to store the spot prices and option values
    Ct = np.empty(nodes)
    St = np.empty(nodes)
   
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
   
    if verbose:
        print(Ct)
       
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            Ct[j] = np.maximum(Ct[j], K - St[j])
            print(Ct)
           
    return Ct[0]



In [138]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = False):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
   
   ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
   
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
   

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
         
    return Ct[0,0]

In [141]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3

In [144]:
callPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff,  verbose = False)
callPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff,  verbose = False)
putPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)

print(f"The European Call Premium: {callPrcE : 0.3f} The American call is {callPrcE : 0.3f}")
print(f"The European Put Premium: {putPrcE : 0.3f} The American put is {putPrcA : 0.3f}")

[56.64406241 33.8147424   0.          0.        ]
[56.64406241 15.04032855  0.          0.        ]
[56.64406241 15.04032855 20.40351726  0.        ]
[33.14931753 15.04032855 20.40351726  0.        ]
[33.14931753 17.48114202 20.40351726  0.        ]
[23.99012609 17.48114202 20.40351726  0.        ]
[ 0.          0.          3.89933488 30.57157332]
[ 0.          2.06235672  3.89933488 30.57157332]
[ 0.          2.06235672 20.40351726 30.57157332]
[ 1.09077967  2.06235672 20.40351726 30.57157332]
[ 1.09077967 11.7087201  20.40351726 30.57157332]
[ 6.67790123 11.7087201  20.40351726 30.57157332]
The European Call Premium:  18.283 The American call is  18.283
The European Put Premium:  5.979 The American put is  6.678


### Problem 6

#### a.

In [148]:
S = 40
K = 40
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 3
h = T / n

In [150]:
u1 = np.exp((r - q) * h + v * np.sqrt(h))
d1 = np.exp((r - q) * h - v * np.sqrt(h))
print(u1, d1)

1.1454617381452392 0.8966038495199921


#### b.

In [151]:
callPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff,  verbose = False)
callPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff,  verbose = False)
putPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)

print(f"The European Call Premium: {callPrcE : 0.3f} The American call is {callPrcE : 0.3f}")
print(f"The European Put Premium: {putPrcE : 0.3f} The American put is {putPrcA : 0.3f}")

[13.01309727  7.05673217  0.          0.        ]
[13.01309727  3.26869392  0.          0.        ]
[13.01309727  3.26869392  7.84406148  0.        ]
[7.73902974 3.26869392 7.84406148 0.        ]
[7.73902974 5.6208478  7.84406148 0.        ]
[6.52754713 5.6208478  7.84406148 0.        ]
[ 0.          0.          3.16660277 11.16886174]
[ 0.          1.65788424  3.16660277 11.16886174]
[ 0.          1.65788424  7.84406148 11.16886174]
[ 0.86799019  1.65788424  7.84406148 11.16886174]
[ 0.86799019  4.8747172   7.84406148 11.16886174]
[ 2.95422756  4.8747172   7.84406148 11.16886174]
The European Call Premium:  4.377 The American call is  4.377
The European Put Premium:  2.809 The American put is  2.954
